apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: voting-app
  name: voting-app
spec:
  ports:
  - name: "5050"
    port: 5050
    targetPort: 80
  selector:
    io.kompose.service: voting-app
status:
  loadBalancer: {}
